React unit tests
JACornelius/onboarding-ui pull request #10
Opened 2018-09-01 23:15 UTC by JACornelius

2018-09-01 23:15 UTC, JACornelius commented
sorry its not ready to review yet. accidentally opened the pr

2018-09-04 18:49 UTC, lee-benjamin requested changes
Can you also give me a quick explanation of what `shallow` and `mount` do? After your changes I'll come over we'll talk about the importance of mocking which I forgot to do earlier.

2018-09-04 18:49 UTC, lee-benjamin commented on __tests__/TimelineTest.js
> +
newlines

2018-09-04 18:49 UTC, lee-benjamin commented on __tests__/TimelineResultCompTest.js
> +
newline

2018-09-04 18:49 UTC, lee-benjamin commented on __tests__/TimelineTest.js
> +	"userName":"Josephine Cornelius",
formatting

2018-09-04 18:49 UTC, lee-benjamin commented on __tests__/TimelineTest.js
> +
in general, remove superfluous new lines

2018-09-04 18:49 UTC, lee-benjamin commented on __tests__/TimelineTest.js
> +		wrapper.setState({timeline: null, error: 'There was a problem on the server side, please try again later.'});
is there a reason for having both kinds of quotes?

2018-09-04 18:49 UTC, lee-benjamin commented on __tests__/TimelineResultCompTest.js
> +		wrapper = mount(React.createElement(TimelineResultComp, {timelineResult: renderedTimeline(mockHttpRespText)}, null));
this test doesn't test the condition you mentioned. Test for the actual profile image URL. Look over the rest of your tests and make sure your tests give heed to your mocked data.

2018-09-04 19:16 UTC, lee-benjamin requested changes

2018-09-04 19:16 UTC, lee-benjamin commented on __tests__/TimelineResultCompTest.js
> +	"userName":"Josephine Cornelius",
Line up the colons-- more readable

2018-09-04 19:16 UTC, lee-benjamin commented on __tests__/TimelineTest.js
> +		"userName":"Josephine Cornelius",
ditto

2018-09-04 19:16 UTC, lee-benjamin commented on __tests__/TimelineTest.js
> +		expect(wrapper.containsMatchingElement(React.createElement(
this style is funky, either one-line this (though it is a long line) or use a local variable to make it more readable

2018-09-04 19:28 UTC, JACornelius commented
I cant find your mount, shallow comment nor the mocking comment so I will just put it here.

Since unit test is meant to test one component/method at a time, sometimes methods rely on other services in order to work. In order to keep it a unit test instead of an integration, we will need to mock "outside" objects and services to test our component or method. For example, lots of unit testing that uses twitter, the twitter obj is mocked

For shallow vs mount. Shallow is on layer, none of the children are rendered. Most of my unit tests are mount because of the many children that need to be checked if they are rendered correctly and because I used a lifecycle function, componentDidMount

2018-09-04 19:49 UTC, lee-benjamin approved these changes

2018-09-04 19:50 UTC, lee-benjamin commented
my bad about the confusing styling comment, good work.

2018-09-04 19:50 UTC, lee-benjamin commented
by the way, get in the habit of doing "squash and merge", pretty sure most teams prefer that.

2018-09-04 19:55 UTC, merged