User timeline
JACornelius/onboarding-ui pull request #12
Opened 2018-09-06 14:20 UTC by JACornelius

2018-09-06 15:17 UTC, lee-benjamin commented
Good practice for dev work on a real team is to rebase your feature branch before you request review.

2018-09-06 22:32 UTC, lee-benjamin commented on src/js/main.js
> +					[React.createElement('div', {className: 'homeTimelineContainer', key: 'homeTimelineCont'},
for the future you can define your own function that stands in for React.createElement so your code is less verbose

2018-09-06 22:32 UTC, lee-benjamin commented on src/js/services.js
> +
new line

2018-09-06 22:32 UTC, lee-benjamin commented on src/sass/style.scss
> +		#homeTimelinePlaceholder, #userTimelinePlaceholder {
formatting

2018-09-07 14:52 UTC, andrewcchau commented on src/js/components.js
> +		return React.createElement('div', {id: this.props.timelinePlaceholder, className: `${this.props.className}`, key: 'timelineResComp'}, this.props.timelineResult);
Is the form for '${this.props.className}' needed?

2018-09-07 14:52 UTC, andrewcchau commented on src/js/components.js
> +		return React.createElement('button', {className: `${this.props.className}`, key: 'timelineButton', onClick: this.props.onClickFunc}, this.props.buttonText);
Same as above

2018-09-07 18:01 UTC, lee-benjamin commented on __tests__/TimelineResultCompTest.js
> +                           "userName":"Josephine Cornelius",
align the keys

2018-09-07 18:02 UTC, lee-benjamin commented on __tests__/TimelineCompTest.js
> +			React.createElement(TimelineResultComp, {timelinePlaceholder: "userTimelinePlaceholder", className: "testResultClass", timelineResult: "testResultOutput"}, null))).toEqual(true);
use local variables and/or shorthand for React.createElement.

2018-09-07 18:02 UTC, lee-benjamin commented on __tests__/TimelineTest.js
> +								 "twitterHandle":"JosephineCorn10",
space after :
align keys

2018-09-07 18:03 UTC, lee-benjamin commented on __tests__/UserTest.js
> +		wrapper = mount(React.createElement(User, {rawUserTweetObj: mockTweetObj, index: 1}, null));
4 or 2 spaces?

2018-09-07 18:09 UTC, lee-benjamin approved these changes
fix them and merge

2018-09-07 18:09 UTC, lee-benjamin commented on src/js/components.js
> +					 	[React.createElement('h2', {className: 'header', key: 'userTimelineHeader'}, 'User Timeline'),
same

2018-09-07 18:09 UTC, lee-benjamin commented on src/sass/style.scss
> +					background-color: #e8f5fd;
spaces

2018-09-07 18:09 UTC, lee-benjamin commented on src/sass/style.scss
> +					background-color: #f5f8fa;
ditto

2018-09-07 18:12 UTC, lee-benjamin requested changes
just kidding, please disable handle for user timeline.

2018-09-07 18:52 UTC, lee-benjamin requested changes

2018-09-07 18:52 UTC, lee-benjamin commented on src/sass/style.scss
> +					background-color: #f5f8fa;
also I neglected to notice this but please don't hardcode the background color... have your tweets share the same css and override the color somehow.

2018-09-07 21:23 UTC, merged